### PR TITLE
Add support to not manage nrpe logging

### PR DESCRIPTION
**Pull request by pirzyk**
Add nrpe.conf.d config directory support

### CODE REVIEW

**Comment by vbotka** [comment]
Thank you for your contribution! I'll review the details soon.

**Comment by vbotka** [comment]
Would it be possible to review the staging branch? I completed the implementation and merged devel into the staging. If there are no objections I'll merge it to master and tag 2.5 in a couple of days.

**Comment by pirzyk** [comment]
staging branch looks good to me.

**Comment by vbotka** [comment]
Merged to master. Tag 2.5.0

**Pull request merged**
